### PR TITLE
Update pawn.json

### PR DESCRIPTION
**Pull request by Fairuz-Afdhal**
Make YSF load properly according to the server version

### CODE REVIEW

**Comment by IllidanS4** [comment]
Thanks for the update. Could you also please tell me what the `runtime.plugins` property means? Also what is the effect of `include_path`?

**Comment by Fairuz-Afdhal** [comment]
> Thanks for the update. Could you also please tell me what the `runtime.plugins` property means? Also what is the effect of `include_path`?

Not sure about the runtimem thing but the include path is exactly what it says, path to the .inc file. I just realized that it's wrong, let me correct it

**Comment by IllidanS4** [comment]
Thinking about this, it would be also nice to get the YSF.cfg file where it belongs, automatically. Could that be achieved?

**Comment by Fairuz-Afdhal** [comment]
There's two methods as far as I know. The current pawn.json takes the include from the source code. The second is to take it from the archive itself like in discord-connector
```
    "resources": [
        {
            "name": "^discord-connector-.+-[Ll]inux\\.tar\\.gz$",
            "platform": "linux",
            "archive": true,
            "includes": ["discord-connector-.+\\/pawno\\/include"],
            "plugins": ["discord-connector-.+\\/plugins\\/discord-connector\\.so"],
            "files": {
                "discord-connector-.+\\/log-core2.so": "log-core2.so"
            }
        },
        {
            "name": "^discord-connector-.+-win(32)?.zip$",
            "platform": "windows",
            "archive": true,
            "includes": ["discord-connector-.+\\/pawno\\/include"],
            "plugins": ["discord-connector-.+\\/plugins\\/discord-connector\\.dll"],
            "files": {
                "discord-connector-.+\\/log-core2.dll": "log-core2.dll"
            }
        }
    ],```
Also the current include_path might be wrong, It might be '\\/' instead of just '\\' I can't test it because sampctl keeps overwriting the file

**Comment by Fairuz-Afdhal** [comment]
> Thinking about this, it would be also nice to get the YSF.cfg file where it belongs, automatically. Could that be achieved?

I think you can achieve it just like what GPS plugin does
```
	"resources": [
		{
			"name": "GPS-windows.zip",
			"platform": "windows",
			"archive": true,
			"includes": [
				"GPS.inc"
			],
			"plugins": [
				"GPS.dll"
			],
			"files": {
				"GPS.dat": "scriptfiles/GPS.dat"
			}
		},
		{
			"name": "GPS-linux.zip",
			"platform": "linux",
			"archive": true,
			"includes": [
				"GPS.inc"
			],
			"plugins": [
				"GPS.so"
			],
			"files": {
				"GPS.dat": "scriptfiles/GPS.dat"
			}
		}
	]
}```

**Comment by IllidanS4** [comment]
Nice! Could you please add it to the file as well?

**Comment by Fairuz-Afdhal** [comment]
That should work

**Comment by IllidanS4** [comment]
I think `"YSF.cfg": "plugins/YSF.cfg"` should be changed to `"plugins/YSF.cfg": "plugins/YSF.cfg"` if it should reflect the path in the archive, otherwise I suppose it is fine.

**Comment by Fairuz-Afdhal** [comment]
> I think `"YSF.cfg": "plugins/YSF.cfg"` should be changed to `"plugins/YSF.cfg": "plugins/YSF.cfg"` if it should reflect the path in the archive, otherwise I suppose it is fine.

I don't think that matters. I can't really test it sorry though

**Pull request merged**
