### PR TITLE
Swap wLRAnalog and wUDAnalog

### PR DESCRIPTION
**Pull request by ziggi**

### CODE REVIEW

**Comment by IllidanS4** [comment]
Which functions does it affects? I haven't seen any bugs related to it.

**Comment by ziggi** [comment]
Yes, because YSF does not use this variables. I use Structs.h in FCNPC and I got some issues with this. You can check GetPlayerKeys function with ID.

**Comment by IllidanS4** [comment]
Ok, then. Thanks for your commits! Approved.

**Comment by ziggi** [comment]
Just for confirmation.

http://wiki.sa-mp.com/wiki/GetPlayerKeys
image

It means that parameters in function have the following pointers:

Pointer | Description
------------- | --------------
params | count
params + 4 | playerid
params + 8 | keys
params + 12 | updown
params + 16 | leftright


Reversed in IDA:
image

Now we have:

Pointer | Description | CPlayer
------------- | -------------- | -------------
params | count
params + 4 | playerid
params + 8 | keys | 10573
params + 12 | updown | 10571
params + 16 | leftright | 10569

image

**Pull request merged**
