### PR TITLE
 Beginning of per-player actors.

### PR DESCRIPTION
**Pull request by myudev**
They are not finished and should not be added in this state, they work
but important questions & features are stll missing.
I didn't had the time & motiviation to finish this, as the codebase is a
"nightmare" to work with IMO.

I added all needed hints for someone to finish this.

**ALSO: I don't even know how much need for something like that is but I saw a actor "streamer" include + a "little discussion" under the thread and just did it so...**

### CODE REVIEW

**Comment by codectile** [comment]
I'd made per-player actors as soon as Kalcor released the actors update, and I observed that we can push the actors limit to around 120(per player). But there were lots of problem with actor related callbacks, which I solved it somehow. Believe me, setting the animations is really a pain.

**Comment by myudev** [comment]
"Actors Update?" Did I miss something?
Setting animations in general or with 120 actors streamed in? I can't imagine why someone would stream-in 120 actors at the same time especially because of their limited functionality compared to full NPC's.
I remember me poking around with animations and I never saw any noticeable problem with actors compared to players.

**Comment by codectile** [comment]
By "actors update", I meant when kalcor added actors to the 0.3.7 client.
I pushed the limit to 120 because I wanted to how many actors can a client tolerate without crashing.
The problem that I mentioned above was related to reversing the internal animation function.

**Comment by myudev** [comment]
Why reverse the "animation function" there's an RPC which we can simply send.
Also it depends if you want to reverse animation logic on the client or server side, if it's on the serverside I don't see the problem, on the clientside it's a bit more "difficult" as some areas are "obfuscated / virtualized" by VMProtect even tho most of the logic is already known

**Comment by IllidanS4** [comment]
Both world-specific and player-specific things are bad approach to something which can be only solved best either with phases or, favourably, with Hide/ShowSomethingForPlayer. However, per-player actor system is apparently something which people want, and can easily get accustomed to, so I'll add this once it is complete.

**Comment by codectile** [comment]
`if it's on the serverside I don't see the problem`
Nice, at least you can explain me what's going on here.

reversed anim function

**Comment by myudev** [comment]
Then give me the offset (from where you reading) I don't like pseudo code. Even tho I don't see anything suspicious other than alignment and compiler optimizations. It still doesn't hinder us setting animations the RPC format is following:
actorid
strlenAnimLib, strAnimLib
strlenAnimName, strAnimName
float "delta"
.. and then the shit ton of parameters

By searching around I also found out (if not already around dunno.) that the SA-MP "hardcoded" streamed "actors" limit is 50.

On Windows 489D50 will send the anim data to a specific player id soaked my information out of that function and still don't see the problem.

oh and "v6" is the length of the "szAnimName" string.

**Comment by codectile** [comment]
Well, I thought that logic might be necessary to set anims, so I tried to figure it out but failed badly due to the obfuscated code mentioned above. By the way, the code which I posted above is from 489D50 and the actor limit is already known to players. 
...and I know that "v6" is length which defined itself later in the code.
Thank you for clearing up my doubt regarding the RPC format, I thought it would be necessary to understand the reversed logic to set the anim properly.

Neither I want to spam this PR, as I have my doubt cleared up we can end our discussion here.

**Pull request closed without merging**
